export { chunk, chunk2 } from './array/chunk'
export { compact } from './array/compact'
export { concat } from './array/concat'
export { map, filter, reduce, find, findIndex, every, some, test } from './array/declares'
export { difference } from './array/difference'
export { drop, dropRight } from './array/drop'
export { flatten1, flatten2 } from './array/flatten'
export { mergeArray } from './array/merge'
export { pull, pullAll } from './array/pull'
export { slice } from './array/slice'
export { unique1, unique2, unique3 } from './array/unique'

export { apply } from './function/apply'
export { bind } from './function/bind'
export { call } from './function/call'
export { debounce } from './function/debounce'
export { throttle } from './function/throttle'

export { clone1, clone2 } from './object/clone'
export { deepClone1, deepClone2, deepClone3, deepClone4 } from './object/deepClone'
export { mergeObject } from './object/merge'
export { myInstanceOf } from './object/myInstanceOf'
export { newInstance } from './object/newInstance'

export { reverseString, palindrome, truncate } from './string'

export { default as axios } from './axios'
export { default as eventBus } from './event-bus'
export { default as Promise } from './promise'
export { default as PubSub } from './pub-sub'